export const ONE_PRODUCT = 'ONE_PRODUCT'
export const ONE_PRODUCT_SUCCESS = 'ONE_PRODUCT_SUCCESS'

export const ALL_PRODUCTS = 'ALL_PRODUCTS'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'